{
  "status": 1,
  "file_name": "simple_calculator_gui.py",
  "content": "\n".join([
    "import tkinter as tk",
    "",
    "def add_numbers():",
    "    num1 = entry1.get()",
    "    num2 = entry2.get()",
    "    result = int(num1) + int(num2)",
    "    label_result.config(text=str(result))",
    "",
    "root = tk.Tk()",
    "root.title('Simple Calculator')",
    "",
    "label1 = tk.Label(root, text='Number 1')",
    "label1.grid(row=0, column=0)",
    "",
    "entry1 = tk.Entry(root)",
    "entry1.grid(row=0, column=1)",
    "",
    "label2 = tk.Label(root, text='Number 2')",
    "label2.grid(row=1, column=0)",
    "",
    "entry2 = tk.Entry(root)",
    "entry2.grid(row=1, column=1)",
    "",
    "button = tk.Button(root, text='Add', command=add_numbers)",
    "button.grid(row=2, column=0, columnspan=2)",
    "",
    "label_result = tk.Label(root, text='')",
    "label_result.grid(row=3, column=0, columnspan=2)",
    "",
    "root.mainloop()"
  ]),
  "message": "simple_calculator_gui.py 파일 생성 완료"
}